---
driver_plugin: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
  attributes:
    bamboo:
      database:
        version: '5.5'
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[bamboo]
    attributes:
      apt:
        compile_time_update: true
      bamboo:
        name: bamboo-dev
        backup:
          enabled: false
          ceph: false
        agent:
          data_dir: /var/bamboo-agent
          home_dir: /opt/bamboo-agent
