language: ruby
rvm:
  - 2.2

sudo: false

#bundler_args: --without development
before_script:
  - bundle exec berks install
script: 
  # - bundle exec knife cookbook test -a -o .
  - bundle exec rake
